post http://localhost:5000/update-token
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxIiwiRFJOIjoiMDI2MDE1Mjg3NzkyNCIsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkZpcnN0TmFtZSI6IkFkbWluIiwiTGFzdE5hbWUiOiJQdWxzYXIiLCJpYXQiOjE3MDE2ODMwMzksImV4cCI6MTcwMTY4NDgzOX0.tz-VKMCQnc00f0k86GaIZyFXFs0u1bGOAJgfyNpAvkA
Content-Type: application/json

{
  "token_ID": "0559 0131 5822 0943 4815",
  "user": "King"
}
###
post http://localhost:5000/turn-meter-on-off
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxIiwiRFJOIjoiMDI2MDE1Mjg3NzkyNCIsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoxLCJGaXJzdE5hbWUiOiJBZG1pbiIsIkxhc3ROYW1lIjoiUHVsc2FyIiwiYWRkcmVzc0NvbXBvbmVudHMiOlsiQzJHVys1Q0oiLCJXaW5kaG9layIsIk5hbWliaWEiXSwiaWF0IjoxNzAxMzM0Nzc2LCJleHAiOjE3MDEzMzY1NzZ9.Xboi3t-VxPGklhJJfTSNxV6m9bhEVyPBZjnfgal8btM

{
  
  "state": "0",
  "reason": "test"
 
}

###

post http://localhost:5000/turn-heater-on-off
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxIiwiRFJOIjoiMDI2MDE1Mjg3NzkyNCIsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoxLCJGaXJzdE5hbWUiOiJBZG1pbiIsIkxhc3ROYW1lIjoiUHVsc2FyIiwiYWRkcmVzc0NvbXBvbmVudHMiOlsiQzJHVys1Q0oiLCJXaW5kaG9layIsIk5hbWliaWEiXSwiaWF0IjoxNzAxMzM0Nzc2LCJleHAiOjE3MDEzMzY1NzZ9.Xboi3t-VxPGklhJJfTSNxV6m9bhEVyPBZjnfgal8btM
Content-Type: application/json

{
  "state": "0",
  "reason": "test"
 
}

###
get http://localhost:5000/get-heater-state
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxIiwiRFJOIjoiMDI2MDE1Mjg3NzkyNCIsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoxLCJGaXJzdE5hbWUiOiJBZG1pbiIsIkxhc3ROYW1lIjoiUHVsc2FyIiwiYWRkcmVzc0NvbXBvbmVudHMiOlsiQzJHVys1Q0oiLCJXaW5kaG9layIsIk5hbWliaWEiXSwiaWF0IjoxNzAxMzM0Nzc2LCJleHAiOjE3MDEzMzY1NzZ9.Xboi3t-VxPGklhJJfTSNxV6m9bhEVyPBZjnfgal8btM

####
get http://localhost:5000/get-meter-state
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxIiwiRFJOIjoiMDI2MDE1Mjg3NzkyNCIsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkFjY2Vzc0xldmVsIjoxLCJGaXJzdE5hbWUiOiJBZG1pbiIsIkxhc3ROYW1lIjoiUHVsc2FyIiwiYWRkcmVzc0NvbXBvbmVudHMiOlsiQzJHVys1Q0oiLCJXaW5kaG9layIsIk5hbWliaWEiXSwiaWF0IjoxNzAxMjczODA4LCJleHAiOjE3MDEyNzU2MDh9.Pgqd5ITpOKFPXoKePAV15AMT1jr5IrElH7GecKKSE8s

####
post http://localhost:5000/signin 
Content-Type: application/json   

{
    "Email": "admin@pulsar.com",
    "Password": "Admin@123"
    
    
    
}

####
get http://ec2-52-4-15-67.compute-1.amazonaws.com:5000/userData
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxIiwiRFJOIjoiMDI2MDE1Mjg3NzkyNCIsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkZpcnN0TmFtZSI6IkFkbWluIiwiTGFzdE5hbWUiOiJQdWxzYXIiLCJpYXQiOjE3MDE3MjAwNjAsImV4cCI6MTcwMTcyMTg2MH0.ufdfnnojlmAng9ORP44nkUoefMMmfYfmJyOkbJEvQo4

###

get http://localhost:5000/meterPower
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxIiwiRFJOIjoiMDI2MDE1Mjg3NzkyNCIsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkZpcnN0TmFtZSI6IkFkbWluIiwiTGFzdE5hbWUiOiJQdWxzYXIiLCJpYXQiOjE3MDE3MjEzODcsImV4cCI6MTcwMTcyMzE4N30.oOBk31Gxqn8nzv7OtvnkPuPh0uP0K6Tg0PJw5dde8g4

###
get http://localhost:5000/getNotifications
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxIiwiRFJOIjoiMDI2MDE1Mjg3NzkyNCIsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkZpcnN0TmFtZSI6IkFkbWluIiwiTGFzdE5hbWUiOiJQdWxzYXIiLCJpYXQiOjE3MDE3NjM5MjAsImV4cCI6MTcwMTc2NTcyMH0.OxwGNT1QC9zhgziVEMi21RAJwM8zr-xJwai7eav9nGA
###

post http://localhost:5000/setNotifications
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxIiwiRFJOIjoiMDI2MDE1Mjg3NzkyNCIsIkVtYWlsIjoiYWRtaW5AcHVsc2FyLmNvbSIsIkZpcnN0TmFtZSI6IkFkbWluIiwiTGFzdE5hbWUiOiJQdWxzYXIiLCJpYXQiOjE3MDE3NjM5MjAsImV4cCI6MTcwMTc2NTcyMH0.OxwGNT1QC9zhgziVEMi21RAJwM8zr-xJwai7eav9nGA

{
  "Alarm": "MeterOff",
  "AlarmType": "Meter Type",
  "Urgency_Type": "1"
}
