post http://ec2-52-4-15-67.compute-1.amazonaws.com:5000/signup
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXRlckRSTiI6IjAyNjAwNjY1NDYxNjkiLCJpYXQiOjE2NzU5MTIwMTF9.4UAhjczOReOuiFg7Gb3Yd9C6E_QwtRx0yvx6wO_YXns
Content-Type: application/json

{
    "Username": "Admin",
    "Password": "Admin@123",
    "DRN": "0260152877924",
    "FirstName": "Admin",
    "LastName": "Pulsar",
    "Email": "admin@pulsar.com",
    "IsActive": 1,
    "RoleName": "admin"
    
}
###
post http://ec2-52-4-15-67.compute-1.amazonaws.com:5000/signin 
Content-Type: application/json   

{
    "Email": "admin@pulsar.com",
    "Password": "Admin@123"
    
    
    
}
###
get http://ec2-52-4-15-67.compute-1.amazonaws.com:5000/protected?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxIiwiTWV0ZXJEUk4iOiIwMjYwMTUyODc3OTI0IiwiRW1haWwiOiJhZG1pbkBwdWxzYXIuY29tIiwiQWNjZXNzTGV2ZWwiOjEsIkZpcnN0TmFtZSI6IkFkbWluIiwiTGFzdE5hbWUiOiJQdWxzYXIiLCJhZGRyZXNzQ29tcG9uZW50cyI6WyJDMkdXKzVDSiIsIldpbmRob2VrIiwiTmFtaWJpYSJdLCJpYXQiOjE3MDEyNzIyNzQsImV4cCI6MTcwMTI3NDA3NH0.b18EA7Qjqwaf3hHfl7ifEiWgc7Lp1M6hxfBTwqIbzqE


###
post http://ec2-52-4-15-67.compute-1.amazonaws.com:5000/forgot-password
Content-Type: application/json

{
    "Email": "admin@pulsar.com",
   
   
}

###

# post http://ec2-52-4-15-67.compute-1.amazonaws.com:5000/turn-meter-on-off
# Content-Type: application/json
# authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIyNiIsIk1ldGVyRFJOIjoiMDI2MDE1Mjg3NzkyNCIsIkVtYWlsIjoiYmFydUBwdWxzYXJlbGVjdHJvbmljLmNvbSIsIkFjY2Vzc0xldmVsIjowLCJGaXJzdE5hbWUiOiJNdWsiLCJMYXN0TmFtZSI6IktlbmR3YSIsImFkZHJlc3NDb21wb25lbnRzIjpbIkMyR1crNUNKIiwiV2luZGhvZWsiLCJOYW1pYmlhIl0sImlhdCI6MTcwMTA5MTMwNiwiZXhwIjoxNzAxMDkzMTA2fQ.mLddzXsS0abMFDnBmNi8dVH5_ZfkQXUNUgdN516UySI

# {
#   "MeterDRN": "0260152877924",
#   "state": 0,
#   "reason": "test",
#   "user": "King"
# }

# ###

# post http://ec2-52-4-15-67.compute-1.amazonaws.com:5000/turn-heater-on-off
# authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIyNiIsIk1ldGVyRFJOIjoiMDI2MDE1Mjg3NzkyNCIsIkVtYWlsIjoiYmFydUBwdWxzYXJlbGVjdHJvbmljLmNvbSIsIkFjY2Vzc0xldmVsIjowLCJGaXJzdE5hbWUiOiJNdWsiLCJMYXN0TmFtZSI6IktlbmR3YSIsImFkZHJlc3NDb21wb25lbnRzIjpbIkMyR1crNUNKIiwiV2luZGhvZWsiLCJOYW1pYmlhIl0sImlhdCI6MTcwMTA5MTMwNiwiZXhwIjoxNzAxMDkzMTA2fQ.mLddzXsS0abMFDnBmNi8dVH5_ZfkQXUNUgdN516UySI
# Content-Type: application/json

# {
#   "state": 0,
#   "reason": "test",
#   "user": "king"
# }

# ###
# get http://ec2-52-4-15-67.compute-1.amazonaws.com:5000/get-heater-state
# Content-Type: application/json
# authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIyNiIsIk1ldGVyRFJOIjoiMDI2MDE1Mjg3NzkyNCIsIkVtYWlsIjoiYmFydUBwdWxzYXJlbGVjdHJvbmljLmNvbSIsIkFjY2Vzc0xldmVsIjowLCJGaXJzdE5hbWUiOiJNdWsiLCJMYXN0TmFtZSI6IktlbmR3YSIsImFkZHJlc3NDb21wb25lbnRzIjpbIkMyR1crNUNKIiwiV2luZGhvZWsiLCJOYW1pYmlhIl0sImlhdCI6MTcwMTA5MTMwNiwiZXhwIjoxNzAxMDkzMTA2fQ.mLddzXsS0abMFDnBmNi8dVH5_ZfkQXUNUgdN516UySI

# ####
# get http://ec2-52-4-15-67.compute-1.amazonaws.com:5000/get-meter-state
# Content-Type: application/json
# authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIyNiIsIk1ldGVyRFJOIjoiMDI2MDE1Mjg3NzkyNCIsIkVtYWlsIjoiYmFydUBwdWxzYXJlbGVjdHJvbmljLmNvbSIsIkFjY2Vzc0xldmVsIjowLCJGaXJzdE5hbWUiOiJNdWsiLCJMYXN0TmFtZSI6IktlbmR3YSIsImFkZHJlc3NDb21wb25lbnRzIjpbIkMyR1crNUNKIiwiV2luZGhvZWsiLCJOYW1pYmlhIl0sImlhdCI6MTcwMTA5MTMwNiwiZXhwIjoxNzAxMDkzMTA2fQ.mLddzXsS0abMFDnBmNi8dVH5_ZfkQXUNUgdN516UySI