post http://localhost:5000/signup
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXRlckRSTiI6IjAyNjAwNjY1NDYxNjkiLCJpYXQiOjE2NzU5MTIwMTF9.4UAhjczOReOuiFg7Gb3Yd9C6E_QwtRx0yvx6wO_YXns
Content-Type: application/json

{
    "Username": "Baru",
    "Password": "12345678",
    "MeterDRN": "0260152877924",
    "FirstName": "Muk",
    "LastName": "Kendwa",
    "Email": "baru@pulsarelectronic.com",
    "IsActive": 1,
    "RoleName": "User"
    
}
###
post http://localhost:3000/signin
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXRlckRSTiI6IjAyNjAwNjY1NDYxNjkiLCJpYXQiOjE2NzU5MTIwMTF9.4UAhjczOReOuiFg7Gb3Yd9C6E_QwtRx0yvx6wO_YXns
Content-Type: application/json   

{
    
    "Password": "12345678",
    "Username": "Baru"
    
    
}

