post http://localhost:4000/signup
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXRlckRSTiI6IjAyNjAwNjY1NDYxNjkiLCJpYXQiOjE2NzU5MTIwMTF9.4UAhjczOReOuiFg7Gb3Yd9C6E_QwtRx0yvx6wO_YXns
Content-Type: application/json

{
    "Username": "admin10",
    "Password": "adminpassword8",
    "FirstName": "Adrian",
    "LastName": "Larreal",
    "Email": "adrian@pulsarelectronic.com",
    "IsActive": 1,
    "RoleName": "Engineer"
    
}