post http://localhost:5000/signup
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXRlckRSTiI6IjAyNjAwNjY1NDYxNjkiLCJpYXQiOjE2NzU5MTIwMTF9.4UAhjczOReOuiFg7Gb3Yd9C6E_QwtRx0yvx6wO_YXns
Content-Type: application/json

{
    "Username": "King",
    "Password": "12345678",
    "MeterDRN": "0260152877924",
    "FirstName": "King",
    "LastName": "Hiholike",
    "Email": "@pulsarelectronic.com",
    "IsActive": 1,
    "RoleName": "User"
    
}
###
post http://localhost:5000/signin 
Content-Type: application/json   

{
    "Email": "baru@pulsarelectronic.com",
    "Password": "12345678"
    
    
    
}
###
get http://localhost:5000/protected?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiI0NSIsIk1ldGVyRFJOIjoiMDI2MDExMTIyMjMzMyIsIkVtYWlsIjoiYmFydUBwdWxzYXJlbGVjdHJvbmljLmNvbSIsIkFjY2Vzc0xldmVsIjpudWxsLCJGaXJzdE5hbWUiOiJNdWsiLCJMYXN0TmFtZSI6IktlbmR3YSIsImFkZHJlc3NDb21wb25lbnRzIjpbIjExMiBCbGFjayBSb2NrIFN0cmVldCIsIldpbmRob2VrIiwiTmFtaWJpYSJdLCJpYXQiOjE3MDA1NjEwNjYsImV4cCI6MTcwMDU2Mjg2Nn0.pScvYtNE7NhvObP7QELz8qEJzIR9R9JPbltSIRnbvvM


###
post http://localhost:5000/forgot-password
Content-Type: application/json

{
  "Email": "baru@pulsarelectronic.com"
}

###

post http://localhost:5000/turn-meter-on-off
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiI0NSIsIk1ldGVyRFJOIjoiMDI2MDExMTIyMjMzMyIsIkVtYWlsIjoiYmFydUBwdWxzYXJlbGVjdHJvbmljLmNvbSIsIkFjY2Vzc0xldmVsIjpudWxsLCJGaXJzdE5hbWUiOiJNdWsiLCJMYXN0TmFtZSI6IktlbmR3YSIsImFkZHJlc3NDb21wb25lbnRzIjpbIjExMiBCbGFjayBSb2NrIFN0cmVldCIsIldpbmRob2VrIiwiTmFtaWJpYSJdLCJpYXQiOjE3MDA1NjEwNjYsImV4cCI6MTcwMDU2Mjg2Nn0.pScvYtNE7NhvObP7QELz8qEJzIR9R9JPbltSIRnbvvM
Content-Type: application/json

{
  "status": 0
}
###

post http://localhost:5000/turn-heater-on-off
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiI0NSIsIk1ldGVyRFJOIjoiMDI2MDExMTIyMjMzMyIsIkVtYWlsIjoiYmFydUBwdWxzYXJlbGVjdHJvbmljLmNvbSIsIkFjY2Vzc0xldmVsIjpudWxsLCJGaXJzdE5hbWUiOiJNdWsiLCJMYXN0TmFtZSI6IktlbmR3YSIsImFkZHJlc3NDb21wb25lbnRzIjpbIjExMiBCbGFjayBSb2NrIFN0cmVldCIsIldpbmRob2VrIiwiTmFtaWJpYSJdLCJpYXQiOjE3MDA1NjEwNjYsImV4cCI6MTcwMDU2Mjg2Nn0.pScvYtNE7NhvObP7QELz8qEJzIR9R9JPbltSIRnbvvM
Content-Type: application/json

{
  "status": 0
}